# Generated by Django 5.0.7 on 2024-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('gender_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.FileField(upload_to='images/gender/')),
            ],
            options={
                'verbose_name': 'Product Gender',
                'verbose_name_plural': 'Product Gender',
            },
        ),
    ]
