# Generated by Django 5.0.7 on 2024-07-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcategorymodel_productsubcategorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productcategorymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
