# Generated by Django 5.0.7 on 2024-07-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productsubcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='category_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='image',
            field=models.FileField(default=1, upload_to='images/category/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='image',
            field=models.FileField(default=1, upload_to='images/subcategory/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='subcategory_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsubcategorymodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategorymodel'),
        ),
    ]
