# Generated by Django 5.0.7 on 2024-07-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcategorymodel_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_product', to='product.productgendermodel'),
        ),
    ]
