# Generated by Django 5.0.7 on 2024-07-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_addcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsubcategorymodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_product', to='product.productsubcategorymodel'),
        ),
    ]
