# Generated by Django 5.0.7 on 2024-07-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_addsubcategorymodel_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcategorymodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_product', to='product.productcategorymodel'),
        ),
        migrations.AlterField(
            model_name='addcategorymodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='product.productmodel'),
        ),
    ]
