# Generated by Django 5.0.7 on 2024-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_addcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('service_place', models.CharField(max_length=32)),
            ],
        ),
    ]
