# Generated by Django 5.0.7 on 2024-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_extragroupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='cover_image_alt',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_image_alt',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size_table_imagealt',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
