# Generated by Django 5.0.7 on 2024-07-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productmodel_cover_image_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tag',
            },
        ),
        migrations.CreateModel(
            name='AddProductTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_tag', to='product.productmodel')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.producttagmodel')),
            ],
        ),
    ]
