# Generated by Django 5.0.7 on 2024-07-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_producttagmodel_addproducttagmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='size_table_imagealt',
            new_name='size_table_image_alt',
        ),
    ]
