# Generated by Django 5.0.7 on 2024-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_descriptions_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
