# Generated by Django 5.0.7 on 2024-08-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantmodel',
            name='item_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
