# Generated by Django 5.0.7 on 2024-08-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productvariantmodel_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantmodel',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Product ID'),
        ),
    ]
