# Generated by Django 5.0.7 on 2024-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productvariantmodel_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addimagegallerymodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/product/gallery/'),
        ),
    ]
