# Generated by Django 5.0.7 on 2024-08-12 05:59

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_addimagegallerymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_cover_image_upload_path),
        ),
    ]
