# Generated by Django 5.0.7 on 2024-08-12 06:57

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_productmodel_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addimagegallerymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_gallery_upload_path),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_description_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size_table_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_size_table_upload_path),
        ),
    ]
