# Generated by Django 5.0.7 on 2024-08-12 07:22

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_addimagegallerymodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='image',
            field=models.FileField(upload_to=upload_path.get_category_upload_path),
        ),
    ]
