# Generated by Django 5.0.7 on 2024-08-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_productgendermodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgendermodel',
            name='image',
            field=models.FileField(upload_to='gender/'),
        ),
    ]
