# Generated by Django 5.0.7 on 2024-08-12 07:57

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_productgendermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgendermodel',
            name='image',
            field=models.FileField(upload_to=upload_path.get_gender_upload_path),
        ),
    ]
