# Generated by Django 5.0.7 on 2024-08-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_productgendermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size_guide',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='video',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
