# Generated by Django 5.0.7 on 2024-08-17 03:41

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_productmodel_details_productmodel_size_guide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=upload_path.get_video_product_upload_path),
        ),
    ]
