# Generated by Django 5.0.7 on 2024-08-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_productmodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='schema_markup',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
