# Generated by Django 5.0.7 on 2024-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_productmodel_schema_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='name_product',
            field=models.CharField(default=21321, max_length=100),
            preserve_default=False,
        ),
    ]
