# Generated by Django 5.0.7 on 2024-08-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_productmodel_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size_guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
