# Generated by Django 5.0.7 on 2024-08-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_productmodel_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
