# Generated by Django 5.0.7 on 2024-08-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_productmodel_application_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name_product',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
