# Generated by Django 5.0.7 on 2024-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_productmodel_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name_product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
