# Generated by Django 5.0.7 on 2024-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_alter_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
