# Generated by Django 5.0.7 on 2024-09-11 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
