# Generated by Django 5.0.7 on 2024-09-11 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_productcategorymodel_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
