# Generated by Django 5.0.7 on 2024-09-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_rename_coupon_couponmodel_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expire',
            field=models.DateTimeField(),
        ),
    ]
