# Generated by Django 5.0.7 on 2024-09-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_couponmodel_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='customer',
            field=models.CharField(max_length=50),
        ),
    ]
