# Generated by Django 5.0.7 on 2024-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_alter_couponmodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='discount_amount',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='discount_percent',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
