# Generated by Django 5.0.7 on 2024-09-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_couponmodel_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='limit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
