# Generated by Django 5.0.7 on 2024-09-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_couponmodel_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='discount_threshold',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
