# Generated by Django 5.0.7 on 2024-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_couponmodel_discount_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
