# Generated by Django 5.0.7 on 2024-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_productcategorymodel_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
