# Generated by Django 5.0.7 on 2024-11-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_alter_productmodel_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=120)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Class Product',
                'verbose_name_plural': 'Class Products',
            },
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_product', to='product.classproductmodel'),
        ),
    ]
