# Generated by Django 5.0.7 on 2024-12-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_classproductmodel_productvariantmodel_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
