# Generated by Django 5.0.7 on 2024-12-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_productcategorymodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
