# Generated by Django 5.0.7 on 2024-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
