# Generated by Django 5.0.7 on 2024-12-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_productmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
