# Generated by Django 5.0.7 on 2025-02-21 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_productbrandmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compression_class', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Compression Class',
                'verbose_name_plural': 'Compression Class',
            },
        ),
        migrations.CreateModel(
            name='SideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Side',
                'verbose_name_plural': 'Side',
            },
        ),
        migrations.RemoveField(
            model_name='productvariantmodel',
            name='classes',
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='compression_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.compressionclassmodel'),
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sidemodel'),
        ),
    ]
