# Generated by Django 5.0.7 on 2025-02-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_compressionclassmodel_sidemodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassProductModel',
        ),
    ]
