# Generated by Django 5.0.7 on 2025-02-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_delete_classproductmodel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariantmodel',
            name='unique_prod_color_size_combo',
        ),
        migrations.AddConstraint(
            model_name='productvariantmodel',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size', 'compression_class', 'side'), name='unique_prod_color_size_combo'),
        ),
    ]
