# Generated by Django 5.0.7 on 2025-02-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_remove_productvariantmodel_unique_prod_color_size_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressionclassmodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sidemodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
