# Generated by Django 5.0.7 on 2025-02-24 04:50

import django.db.models.deletion
import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_compressionclassmodel_priority_sidemodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrandmodel',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_logo_upload_path),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productbrandmodel'),
        ),
    ]
