# Generated by Django 5.0.7 on 2025-03-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_productbrandmodel_brand_logo_productmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
