# Generated by Django 5.0.7 on 2025-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_alter_productcategorymodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommademodel',
            name='phone_prefix',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
