# Generated by Django 5.0.7 on 2025-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_custommademodel_phone_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertypemodel',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
