# Generated by Django 5.0.7 on 2025-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_customertypemodel_is_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyareamodel',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classnumbermodel',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hearaboutusmodel',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producttypemodel',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatmentcategorymodel',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
