# Generated by Django 5.0.7 on 2025-04-29 04:17

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_bodyareamodel_is_enable_classnumbermodel_is_enable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTestimonialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CustomMadePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=upload_path.get_custom_made_upload_path)),
                ('content1_text', models.TextField()),
                ('content1_right_image', models.ImageField(upload_to=upload_path.get_custom_made_upload_path)),
                ('content1_mid_image', models.ImageField(upload_to=upload_path.get_custom_made_upload_path)),
                ('content1_left_image', models.ImageField(upload_to=upload_path.get_custom_made_upload_path)),
                ('content2_text', models.TextField()),
                ('content2_image', models.ImageField(upload_to=upload_path.get_custom_made_upload_path)),
                ('content2_link', models.CharField(max_length=128)),
                ('content3_text', models.TextField()),
                ('content3_right', models.TextField()),
                ('content3_mid', models.TextField()),
                ('content3_left', models.TextField()),
                ('content4_text', models.TextField()),
                ('content4_image', models.ImageField(upload_to=upload_path.get_custom_made_upload_path)),
                ('content4_right', models.TextField()),
                ('content4_mid', models.TextField()),
                ('content4_left', models.TextField()),
                ('content4_link_explore', models.CharField(max_length=128)),
                ('content4_link_place_order', models.CharField(max_length=128)),
                ('customer_testimonials', models.TextField()),
            ],
        ),
    ]
