# Generated by Django 5.0.7 on 2025-04-29 04:40

import django.db.models.deletion
import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_customertestimonialsmodel_custommadepagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to=upload_path.get_brand_logo_upload_path)),
                ('image2', models.ImageField(upload_to=upload_path.get_brand_logo_upload_path)),
                ('image3', models.ImageField(upload_to=upload_path.get_brand_logo_upload_path)),
                ('content', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productbrandmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BrandPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=upload_path.get_brand_logo_upload_path)),
                ('content1_title', models.CharField(max_length=64)),
                ('content1_image', models.ImageField(upload_to=upload_path.get_brand_logo_upload_path)),
                ('content1_text', models.TextField()),
                ('content2_text', models.TextField()),
                ('content2_right_image', models.ImageField(upload_to=upload_path.get_brand_logo_upload_path)),
                ('content2_right', models.TextField()),
                ('content2_mid_image', models.ImageField(upload_to=upload_path.get_brand_logo_upload_path)),
                ('content2_mid', models.TextField()),
                ('content2_left_image', models.ImageField(upload_to=upload_path.get_brand_logo_upload_path)),
                ('content2_left', models.TextField()),
                ('contact_image', models.ImageField(upload_to=upload_path.get_brand_logo_upload_path)),
                ('contact_text', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productbrandmodel')),
            ],
        ),
    ]
