# Generated by Django 5.0.7 on 2025-04-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0075_brandcartmodel_brandpagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommadepagemodel',
            name='image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
