# Generated by Django 5.0.7 on 2025-04-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_custommadepagemodel_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpagemodel',
            name='image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
