# Generated by Django 5.0.7 on 2025-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_custommademodel_other_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrandmodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
