# Generated by Django 5.0.7 on 2025-04-30 14:39

import django.db.models.deletion
import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_alter_productbrandmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandcartmodel',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='brandcartmodel',
            name='image1_alt',
        ),
        migrations.RemoveField(
            model_name='brandcartmodel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='brandcartmodel',
            name='image3',
        ),
        migrations.CreateModel(
            name='BrandCartImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=upload_path.get_brand_cart_upload_path)),
                ('image_alt', models.CharField(max_length=64)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('brand_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.brandcartmodel')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
