# Generated by Django 5.0.7 on 2025-04-30 14:53

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_remove_brandcartmodel_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandpagemodel',
            old_name='image',
            new_name='image_desktop',
        ),
        migrations.RenameField(
            model_name='custommadepagemodel',
            old_name='image',
            new_name='image_desktop',
        ),
        migrations.AddField(
            model_name='brandpagemodel',
            name='image_mobile',
            field=models.ImageField(default=1, upload_to=upload_path.get_brand_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommadepagemodel',
            name='image_mobile',
            field=models.ImageField(default=1, upload_to=upload_path.get_custom_made_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custommademodel',
            name='other_customer_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
