# Generated by Django 5.0.7 on 2025-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_rename_image_brandpagemodel_image_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimagegallerymodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='brandpagemodel',
            name='contact_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandpagemodel',
            name='content1_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandpagemodel',
            name='content2_left_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandpagemodel',
            name='content2_mid_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandpagemodel',
            name='content2_right_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommadepagemodel',
            name='content1_left_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommadepagemodel',
            name='content1_mid_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommadepagemodel',
            name='content1_right_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommadepagemodel',
            name='content2_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommadepagemodel',
            name='content4_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='brand_logo_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgendermodel',
            name='image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
