# Generated by Django 5.0.7 on 2025-05-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_addimagegallerymodel_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrandmodel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
