# Generated by Django 5.0.7 on 2025-05-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0085_alter_productbrandmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrandmodel',
            name='slug',
            field=models.SlugField(default=11),
        ),
    ]
