# Generated by Django 5.0.7 on 2025-05-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0087_alter_productbrandmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommadepagemodel',
            name='content1_left_title',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommadepagemodel',
            name='content1_mid_title',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommadepagemodel',
            name='content1_right_title',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
