# Generated by Django 5.0.7 on 2025-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0088_custommadepagemodel_content1_left_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcartimagemodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='brandpagemodel',
            name='contact_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='brandpagemodel',
            name='content1_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='brandpagemodel',
            name='content2_left_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='brandpagemodel',
            name='content2_mid_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='brandpagemodel',
            name='content2_right_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='brandpagemodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content1_left_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content1_mid_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content1_right_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content2_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content4_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productcategorymodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productgendermodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategorymodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
