# Generated by Django 5.0.7 on 2025-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0089_alter_brandcartimagemodel_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content1_left_title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content1_mid_title',
            field=models.CharField(max_length=326),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content1_right_title',
            field=models.CharField(max_length=32),
        ),
    ]
