# Generated by Django 5.0.7 on 2025-05-11 03:11

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0090_alter_custommadepagemodel_content1_left_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrandmodel',
            name='contact_image',
            field=models.ImageField(default=1, upload_to=upload_path.get_brand_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='contact_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='contact_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content1_image',
            field=models.ImageField(default=1, upload_to=upload_path.get_brand_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content1_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content1_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content1_title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_left',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_left_image',
            field=models.ImageField(default=1, upload_to=upload_path.get_brand_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_left_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_mid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_mid_image',
            field=models.ImageField(default=1, upload_to=upload_path.get_brand_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_mid_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_right',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_right_image',
            field=models.ImageField(default=1, upload_to=upload_path.get_brand_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_right_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='content2_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='image_desktop',
            field=models.ImageField(default=1, upload_to=upload_path.get_brand_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='image_mobile',
            field=models.ImageField(default=1, upload_to=upload_path.get_brand_upload_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BrandPageModel',
        ),
    ]
