# Generated by Django 5.0.7 on 2025-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_productbrandmodel_contact_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrandmodel',
            name='active_page',
            field=models.BooleanField(default=False),
        ),
    ]
