# Generated by Django 5.0.7 on 2025-05-14 16:14

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0092_productbrandmodel_active_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrandmodel',
            name='contact_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='contact_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content1_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content1_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_left',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_left_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_mid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_mid_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_right',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_right_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='image_desktop',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_upload_path),
        ),
    ]
