# Generated by Django 5.0.7 on 2025-05-18 04:04

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_alter_productbrandmodel_contact_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommademodel',
            name='attach_file',
            field=models.FileField(default=1, upload_to=upload_path.get_attach_file_upload_path),
            preserve_default=False,
        ),
    ]
