# Generated by Django 5.0.7 on 2025-05-18 07:40

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0094_custommademodel_attach_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommademodel',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to=upload_path.get_attach_file_upload_path),
        ),
    ]
