# Generated by Django 5.0.7 on 2025-05-25 04:13

import django.db.models.deletion
import django.utils.timezone
import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_alter_custommademodel_attach_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommademodel',
            name='attach_file',
        ),
        migrations.AddField(
            model_name='custommademodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CustomMadeAttachFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_file', models.FileField(blank=True, null=True, upload_to=upload_path.get_attach_file_upload_path)),
                ('custom_made', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.custommademodel')),
            ],
        ),
    ]
