# Generated by Django 5.0.7 on 2025-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0096_remove_custommademodel_attach_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategorymodel',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
