# Generated by Django 5.0.7 on 2025-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_alter_productsubcategorymodel_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addimagegallerymodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='brandcartimagemodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='custommademodel',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='custommademodel',
            name='phone_prefix',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content1_left_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content1_mid_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content1_right_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content2_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='content4_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='custommadepagemodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='brand_logo_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='contact_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content1_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_left_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_mid_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_right_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productcategorymodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productgendermodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size_table_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategorymodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
