# Generated by Django 5.0.7 on 2025-06-09 10:14

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0100_productsubcategorymodel_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrandmodel',
            name='contact_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_c_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content1_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_c1_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_left_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_c2l_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_mid_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_c2m_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='content2_right_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_c2r_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='image_desktop',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_desktop_upload_path),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_brand_mobile_upload_path),
        ),
    ]
