# Generated by Django 5.0.7 on 2025-06-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0101_alter_productbrandmodel_contact_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrandmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productbrandmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
