# Generated by Django 5.0.7 on 2025-06-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0102_alter_productbrandmodel_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommademodel',
            name='new_comment',
            field=models.BooleanField(default=True),
        ),
    ]
