# Generated by Django 5.0.7 on 2025-08-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0103_custommademodel_new_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrandmodel',
            name='canonical',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='productbrandmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
