# Generated by Django 5.0.7 on 2025-08-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0104_productbrandmodel_canonical_productbrandmodel_follow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_variant', models.CharField(max_length=32)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Model Variant',
                'verbose_name_plural': 'Model Variant',
            },
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_product', to='product.colorproductmodel'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_product', to='product.sizeproductmodel'),
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.modelvariant'),
        ),
    ]
