# Generated by Django 5.0.7 on 2024-09-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_currentaddressmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='emirats',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
