# Generated by Django 5.0.7 on 2025-01-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_addressmodel_iban_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefix_number',
            field=models.CharField(default=971, max_length=8),
            preserve_default=False,
        ),
    ]
