# Generated by Django 5.0.7 on 2025-01-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_prefix_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefix_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
