# Generated by Django 5.0.7 on 2024-07-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16, unique=True)),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BlogImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/blog/')),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blogs Tag',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='blog/cover/')),
                ('cover_image_alt', models.CharField(max_length=32)),
                ('banner', models.ImageField(upload_to='blog/banner/')),
                ('banner_alt', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=250)),
                ('title_image', models.ImageField(upload_to='blog/title/')),
                ('title_image_alt', models.CharField(max_length=32)),
                ('short_description', models.TextField(max_length=60)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=24)),
                ('slug', models.SlugField(unique=True)),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=150)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddBlogTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tag', to='blog.blogmodel')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.blogtagmodel')),
            ],
        ),
    ]
