# Generated by Django 5.0.7 on 2024-07-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtagmodel',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
