# Generated by Django 5.0.7 on 2024-07-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogtagmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblogtagmodel',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tag', to='blog.blogmodel'),
        ),
    ]
