# Generated by Django 5.0.7 on 2024-08-12 06:57

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='banner',
            field=models.ImageField(upload_to=upload_path.get_banner_blog_upload_path),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='cover_image',
            field=models.ImageField(upload_to=upload_path.get_cover_blog_upload_path),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title_image',
            field=models.ImageField(upload_to=upload_path.get_title_blog_upload_path),
        ),
    ]
