# Generated by Django 5.0.7 on 2024-08-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogmodel_banner_alter_blogmodel_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='schema_markup',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
