# Generated by Django 5.0.7 on 2024-07-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='banner_alt',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='cover_image_alt',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_image_alt',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
