# Generated by Django 5.0.7 on 2024-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogmodel_schema_markup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='schema_markup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
