# Generated by Django 5.0.7 on 2024-07-16 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogmodel_banner_alt_blogmodel_cover_image_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16)),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategorymodel'),
        ),
    ]
