# Generated by Django 5.0.7 on 2024-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcategorymodel_alter_blogmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='category',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
