# Generated by Django 5.0.7 on 2024-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogmodel_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
