# Generated by Django 5.0.7 on 2024-08-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogcategorymodel_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
