# Generated by Django 5.0.7 on 2024-07-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimagemodel',
            name='type',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
