# Generated by Django 5.0.7 on 2024-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogcategorymodel_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='banner_alt',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='cover_image_alt',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title_image_alt',
            field=models.CharField(max_length=125),
        ),
    ]
