# Generated by Django 5.0.7 on 2024-09-15 05:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_commentblog_blog_alter_commentblog_reply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentBlog',
            new_name='CommentBlogModel',
        ),
    ]
