# Generated by Django 5.0.7 on 2024-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_commentblog_commentblogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
