# Generated by Django 5.0.7 on 2024-09-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_commentblog_commentblogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorymodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
