# Generated by Django 5.0.7 on 2024-09-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogcategorymodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
