# Generated by Django 5.0.7 on 2024-09-16 05:52

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogcategorymodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_banner_blog_upload_path),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_title_blog_upload_path),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title_image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
