# Generated by Django 5.0.7 on 2024-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogmodel_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagemodel',
            name='image',
            field=models.ImageField(max_length=500, upload_to='blog/blog/'),
        ),
    ]
