# Generated by Django 5.0.7 on 2024-09-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='role',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
