# Generated by Django 5.0.7 on 2024-11-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogmodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblogmodel',
            name='new_comment',
            field=models.BooleanField(default=True),
        ),
    ]
