# Generated by Django 5.0.7 on 2025-02-24 04:50

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_commentblogmodel_new_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to=upload_path.get_author_upload_path),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='read_duration',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
