# Generated by Django 5.0.7 on 2025-02-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_blogmodel_created_alter_blogmodel_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
        migrations.CreateModel(
            name='AddCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategorymodel')),
            ],
        ),
    ]
