# Generated by Django 5.0.7 on 2025-02-24 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_blogmodel_category_addcategorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcategorymodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_blog', to='blog.blogmodel'),
        ),
    ]
