# Generated by Django 5.0.7 on 2025-03-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_addcategorymodel_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='author_image',
        ),
    ]
