# Generated by Django 5.0.7 on 2025-03-01 04:38

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_blogmodel_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to=upload_path.get_author_upload_path)),
            ],
        ),
    ]
