# Generated by Django 5.0.7 on 2025-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_blogmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='short_description',
            field=models.TextField(max_length=160),
        ),
    ]
