# Generated by Django 5.0.7 on 2025-03-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_blogmodel_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='banner_alt',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='role',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_image',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_image_alt',
        ),
    ]
