# Generated by Django 5.0.7 on 2025-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_blogmodel_banner_remove_blogmodel_banner_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
