# Generated by Django 5.0.7 on 2025-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_blogmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorblogmodel',
            name='author_image_alt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blogimagemodel',
            name='image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
