# Generated by Django 5.0.7 on 2025-05-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_authorblogmodel_author_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
