# Generated by Django 5.0.7 on 2025-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_blogcategorymodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorblogmodel',
            name='author_image_alt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='blogimagemodel',
            name='image_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='cover_image_alt',
            field=models.CharField(max_length=256),
        ),
    ]
