# Generated by Django 5.0.7 on 2024-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'video',
            },
        ),
    ]
