# Generated by Django 5.0.7 on 2024-07-22 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_commenthomemodel_active_commenthomemodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslidermodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bannerslidermodel',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
