# Generated by Django 5.0.7 on 2024-08-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bannerslidermodel_active_bannerslidermodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslidermodel',
            name='banner',
            field=models.ImageField(upload_to='settings/banner-slide/', verbose_name='image (1455*505 px)'),
        ),
    ]
