# Generated by Django 5.0.7 on 2024-08-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bannerslidermodel_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_about_title', models.TextField()),
                ('home_about_description', models.TextField()),
            ],
        ),
    ]
