# Generated by Django 5.0.7 on 2024-08-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contenthomemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslidermodel',
            name='banner_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
