# Generated by Django 5.0.7 on 2024-08-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bannerslidermodel_banner_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_shop/images/')),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
