# Generated by Django 5.0.7 on 2024-08-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_logomodel_seohomemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomodel',
            name='logo_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
