# Generated by Django 5.0.7 on 2024-09-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_seohomemodel_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslidermodel',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
