# Generated by Django 5.0.7 on 2024-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_newslettermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslidermodel',
            name='banner_alt',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='logomodel',
            name='logo_alt',
            field=models.CharField(max_length=125),
        ),
    ]
