# Generated by Django 5.0.7 on 2024-09-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_bannerslidermodel_banner_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact User Submit',
                'verbose_name_plural': 'Contact User Submit',
            },
        ),
    ]
