# Generated by Django 5.0.7 on 2024-10-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contactsubmitmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('chat_id', models.CharField(max_length=64)),
            ],
        ),
    ]
