# Generated by Django 5.0.7 on 2024-11-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_telegrambotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCarePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundPolicyPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitemapPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleInquiryPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
