# Generated by Django 5.0.7 on 2024-12-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_aboutpagemodel_blogpagemodel_careerpagemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenthomemodel',
            old_name='home_about_description',
            new_name='home_content',
        ),
        migrations.RemoveField(
            model_name='contenthomemodel',
            name='home_about_title',
        ),
    ]
