# Generated by Django 5.0.7 on 2024-12-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_home_about_description_contenthomemodel_home_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenthomemodel',
            old_name='home_content',
            new_name='content',
        ),
    ]
