# Generated by Django 5.0.7 on 2024-12-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_home_content_contenthomemodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslidermodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
