# Generated by Django 5.0.7 on 2025-01-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_bannerslidermodel_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSliderMobileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='settings/banner-slide-mobile/', verbose_name='image (1455*505 px)')),
                ('banner_alt', models.CharField(max_length=125)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Slider Mobile',
                'verbose_name_plural': 'Banner Sliders Mobile',
            },
        ),
    ]
