# Generated by Django 5.0.7 on 2025-04-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_bannerslidermobilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Content 2',
                'verbose_name_plural': 'Content 2',
            },
        ),
        migrations.CreateModel(
            name='Content3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Content 3',
                'verbose_name_plural': 'Content 3',
            },
        ),
        migrations.RenameModel(
            old_name='ContentHomeModel',
            new_name='Content1Model',
        ),
        migrations.AlterModelOptions(
            name='content1model',
            options={'verbose_name': 'Content 1', 'verbose_name_plural': 'Content 1'},
        ),
    ]
