# Generated by Django 5.0.7 on 2025-04-29 03:44

import upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_content2model_content3model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content1model',
            name='explore_link',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content1model',
            name='image',
            field=models.ImageField(default=1, upload_to=upload_path.get_content_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content1model',
            name='left_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content1model',
            name='left_content_icon',
            field=models.ImageField(default=1, upload_to=upload_path.get_content_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content1model',
            name='left_content_title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content1model',
            name='place_order_link',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content1model',
            name='right_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content1model',
            name='right_content_icon',
            field=models.ImageField(default=1, upload_to=upload_path.get_content_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content1model',
            name='right_content_title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content2model',
            name='custom_made_link',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content2model',
            name='image',
            field=models.ImageField(default=1, upload_to=upload_path.get_content_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content2model',
            name='learn_more_link',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content2model',
            name='left_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content2model',
            name='mid_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content2model',
            name='right_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='discover_link',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='left_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='left_content_icon',
            field=models.ImageField(default=1, upload_to=upload_path.get_content_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='left_content_title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='left_image',
            field=models.ImageField(default=1, upload_to=upload_path.get_content_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='mid_image',
            field=models.ImageField(default=1, upload_to=upload_path.get_content_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='request_link',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='right_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='right_content_icon',
            field=models.ImageField(default=1, upload_to=upload_path.get_content_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='right_content_title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='right_image',
            field=models.ImageField(default=1, upload_to=upload_path.get_content_upload_path),
            preserve_default=False,
        ),
    ]
