# Generated by Django 5.0.7 on 2025-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_faqmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content1model',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='content1model',
            old_name='left_content_title',
            new_name='image_alt',
        ),
        migrations.RenameField(
            model_name='content1model',
            old_name='right_content_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='content2model',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='content2model',
            old_name='custom_made_link',
            new_name='explore_link',
        ),
        migrations.RenameField(
            model_name='content3model',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='content1model',
            name='left_content',
        ),
        migrations.RemoveField(
            model_name='content1model',
            name='left_content_icon',
        ),
        migrations.RemoveField(
            model_name='content1model',
            name='place_order_link',
        ),
        migrations.RemoveField(
            model_name='content1model',
            name='right_content',
        ),
        migrations.RemoveField(
            model_name='content1model',
            name='right_content_icon',
        ),
        migrations.RemoveField(
            model_name='content2model',
            name='learn_more_link',
        ),
        migrations.RemoveField(
            model_name='content2model',
            name='left_content',
        ),
        migrations.RemoveField(
            model_name='content2model',
            name='mid_content',
        ),
        migrations.RemoveField(
            model_name='content2model',
            name='right_content',
        ),
        migrations.RemoveField(
            model_name='content3model',
            name='discover_link',
        ),
        migrations.AddField(
            model_name='content1model',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content2model',
            name='image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content2model',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content2model',
            name='title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='left_content_icon_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='left_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='mid_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content3model',
            name='right_content_icon_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='right_image_alt',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content3model',
            name='title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
