# Generated by Django 5.0.7 on 2025-05-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_content_content1model_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content1model',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='content2model',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='content3model',
            name='priority',
        ),
    ]
