# Generated by Django 5.0.7 on 2025-05-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_content1model_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenthomemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
