# Generated by Django 5.0.7 on 2025-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_commenthomemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslidermobilemodel',
            name='banner_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='bannerslidermodel',
            name='banner_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='content1model',
            name='image_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='content2model',
            name='image_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='content3model',
            name='left_content_icon_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='content3model',
            name='left_image_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='content3model',
            name='mid_image_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='content3model',
            name='right_content_icon_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='content3model',
            name='right_image_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='logomodel',
            name='logo_alt',
            field=models.CharField(max_length=256),
        ),
    ]
