# Generated by Django 5.0.7 on 2025-06-10 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_bannerslidermobilemodel_banner_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmitmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
