# Generated by Django 5.0.7 on 2025-06-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_contactsubmitmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmitmodel',
            name='new_comment',
            field=models.BooleanField(default=True),
        ),
    ]
