# Generated by Django 5.0.7 on 2025-08-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_contactsubmitmodel_new_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDeliveryPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermConditionPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('follow', models.BooleanField(default=False)),
                ('index', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('schema_markup', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
