# Generated by Django 5.0.7 on 2024-08-13 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderstatusmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='sent',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_order', to='order.orderstatusmodel'),
            preserve_default=False,
        ),
    ]
