# Generated by Django 5.0.7 on 2024-09-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_options_remove_ordermodel_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='ref_id',
            new_name='transaction_ref',
        ),
    ]
