# Generated by Django 5.0.7 on 2024-09-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_ref_id_ordermodel_transaction_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='transaction_ref',
            new_name='ref_id',
        ),
    ]
