# Generated by Django 5.0.7 on 2024-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordermodel_transaction_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='completed',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
