# Generated by Django 5.0.7 on 2024-09-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderitemmodel_completed_ordermodel_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='completed',
        ),
    ]
