# Generated by Django 5.0.7 on 2024-09-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_ordermodel_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='discount_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='selling_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
