# Generated by Django 5.0.7 on 2024-09-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderitemmodel_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='item_id',
        ),
    ]
