# Generated by Django 5.0.7 on 2024-09-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_orderitemmodel_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='trace',
        ),
    ]
