# Generated by Django 5.0.7 on 2024-09-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_orderitemmodel_trace'),
        ('product', '0051_alter_couponmodel_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.couponmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_discount',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
