# Generated by Django 5.0.7 on 2024-10-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_ordermodel_coupon_ordermodel_total_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total_amount',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
