# Generated by Django 5.0.7 on 2024-10-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_ordermodel_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryShippingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=24)),
                ('threshold_free', models.CharField(max_length=9)),
                ('shipping_fee', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=24)),
                ('city', models.CharField(blank=True, max_length=24, null=True)),
                ('threshold_free', models.CharField(max_length=9)),
                ('shipping_fee', models.CharField(max_length=9)),
            ],
        ),
    ]
