# Generated by Django 5.0.7 on 2024-10-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_countryshippingmodel_shippingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryShippingModel',
        ),
    ]
