# Generated by Django 5.0.7 on 2024-10-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_delete_countryshippingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=24)),
                ('threshold_free', models.CharField(max_length=9)),
                ('shipping_fee', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='shippingmodel',
            name='city',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='shippingmodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shippingcountrymodel'),
        ),
    ]
