# Generated by Django 5.0.7 on 2024-10-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_shippingcountrymodel_alter_shippingmodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcountrymodel',
            name='delivery_day',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingmodel',
            name='delivery_day',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
