# Generated by Django 5.0.7 on 2024-10-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_shippingcountrymodel_delivery_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmodel',
            name='city',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
