# Generated by Django 5.0.7 on 2024-10-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_shippingmodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shipping',
            field=models.CharField(default='0', max_length=9),
        ),
    ]
